DjangoBooks/DjangoBooks/urls.py
from django.conf.urls import url, include
# from django.contrib import admin
from django.views.generic import RedirectView
from books.index_handle import index_handle

import xadmin
"""
第一种首页配置url(r"^index/$", index_handle.index_handle), 采用一级路由
第二种首页配置url(r'^$',RedirectView.as_view(url= "books/index")), 采用二级路由重定向路径
"""
urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    # url(r'^$',index_handle),
    url(r'^xadmin/',xadmin.site.urls),
    url(r'^ueditor/',include('DjangoUeditor.urls')),
    url(r'^$',RedirectView.as_view(url= "books/index")),
    url(r'^books/',include('books.urls')),
    url(r'^user/',include('user_center.urls')),
    url(r'^message/',include('message.urls')),
    url(r'^apis/', include("drf_apis.urls")),
    url(r'^statistic/',include('statistic.urls')),
    url(r'^cart/',include('commerce.urls')),
]

DjangoBooks/apps/message/urls.py
from django.conf.urls import url

from message import message_handler, comments_handler

"""
第一种首页配置url(r"^index/$", index_handle.index_handle), 采用一级路由
第二种首页配置url(r'^$',RedirectView.as_view(url= "books/index")), 采用二级路由重定向路径
"""
app_name = "message"
urlpatterns = [
    url(r'^art/(?P<art_pk>[0-9]+)/$',comments_handler.art_comment,name="art_comment"),
    url(r"^$", message_handler.MessageSubmitHandlerV2, name='msg_form'),
]

DjangoBooks/extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

DjangoBooks/apps/message/models.py
from DjangoUeditor.models import UEditorField
from django.db import models
from django.utils import timezone
# Create your models here.
from books.models import Art
from DjangoBooks.settings import DB_FIELD_VALID_CHOICES


class Comment(models.Model):
    name = models.CharField(max_length=50, verbose_name="评论者")
    title = models.CharField(max_length=200, verbose_name="评论标题")
    text = models.TextField(verbose_name="评论内容")
    created_time = models.DateTimeField(default=timezone.now, db_index=True, verbose_name="创建时间")
    art = models.ForeignKey(Art, verbose_name="关联的小说")
    flag = models.IntegerField(default=0, verbose_name="控制字段", choices=DB_FIELD_VALID_CHOICES)

    def __str__(self):
        return self.title

    class Meta:
        db_table = "comments"
        verbose_name = "用户评论"
        verbose_name_plural = verbose_name
        ordering = ["-created_time"]

class UserMessage(models.Model):
    name = models.CharField(max_length=20, verbose_name="用户名")
    email = models.EmailField(verbose_name="邮箱")
    address = models.CharField(max_length=100, verbose_name="地址")
    # message = models.TextField(verbose_name="留言内容")
    message = UEditorField(verbose_name="留言内容", width=1000, height=600,
                           imagePath="msg_ups/ueditor/",
                           filePath="msg_ups/ueditor/",
                           blank=True, toolbars="full", default='')
    create_time = models.DateTimeField(default=timezone.now, verbose_name="创建时间")

    def __str__(self):
        return self.name

    class Meta:
        db_table = "user_message"
        verbose_name = "用户留言"
        verbose_name_plural = verbose_name
        ordering = ["-create_time"]

DjangoBooks/apps/message/forms.py
'''
评论的表单
'''
from django import forms
from django.core.exceptions import ValidationError
from django.forms import widgets

from message import models
from message.models import Comment


'''
用户评论的form表单
'''


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'title', 'text']

class UserMessageForm(forms.Form):
    name = forms.CharField(
        label="用户名",
        required=True,
        min_length=5,
        max_length=20,
        # <input type="text" class="form-control" />
        widget=widgets.TextInput(attrs={
            "class": "form-control",
            "placeholder": "请输入您的姓名, 长度为5~20",
        }),
        error_messages={
            "required": "用户名不能为空",
            "min_length": "不行, 长度小于5",
            "max_length": "sorry, 长度太长，超过20",
        })
    email = forms.EmailField(
        label="邮箱",
        required=True,
        widget=widgets.TextInput(attrs={
            "placeholder": "请输入邮箱",
        }),
        error_messages={
            "required": "邮箱不能为空！",
            "invalid": "抱歉，请输入合法的邮箱！",
        }
    )
    address = forms.CharField(
        label="地址",
        widget=widgets.TextInput(attrs={"placeholder": "请输入地址"}),
        max_length=200,
    )
    message = forms.CharField(
        label="留言",
        widget=widgets.Textarea(attrs={"placeholder": "请输入用户留言信息"})
    )

    def clean_name(self):
        # 对name字段进行扩展校验，在models层进行db是否存在校验
        name = self.cleaned_data.get("name")
        users = models.UserMessage.objects.filter(name=name).count()
        if users:
            raise ValidationError("用户已存在！")
        return name

    def clean_email(self):
        email = self.cleaned_data.get("email")
        users = models.UserMessage.objects.filter(email=email).count()
        if users:
            raise ValidationError("邮箱已存在！")
        return email

DjangoBooks/apps/message/views.py
from django.shortcuts import render

# Create your views here.

DjangoBooks/apps/message/templates/msg_form.html
{% extends "base_tmp.html" %}


{% block css %}

    <link rel="stylesheet" href="/static/base/css/msg_style.css">

{% endblock %}

{% block content %}
    <!--内容-->
<div class="container" style="margin-top:76px">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title"><span class="glyphicon glyphicon-list-alt"></span>&nbsp;留言板</h3>
                </div>
                <div class="panel-body">

                    <form action="{% url 'message:msg_form' %}" method="post" class="smart-green">

                        <h1>留言信息
                            <span>请留下你的信息.</span>
                        </h1>
                        <!--
                        {{ form.as_p }}
                        -->
                        {{form.name.label}}
                        <span style="color: red">{{form.name.errors}}</span>
                        {{form.name}}


                        {{form.email.label}}
                        <span style="color: red">{{form.email.errors}}</span>
                        {{form.email}}


                        {{form.address.label}}
                         <span style="color: red">{{form.address.errors}}</span>
                        {{form.address}}


                        {{form.message.label}}
                        <span style="color: red">{{form.message.errors}}</span>
                        {{form.message}}

                        <div class="success-msg"></div>
                        <label>
                            <span>&nbsp;</span>
                            <input type="submit" class="button" value="提交"/>
                        </label>

                    </form>

                </div>
            </div>
        </div>

    </div>
</div>
<!--内容-->


{% endblock %}

DjangoBooks/apps/message/templates/msg_list.html
{% extends "base_tmp.html" %}

{% block content %}
<!--内容-->
<div class="container" style="margin-top:76px">
    <div class="row">
        {% for v in  data %}
        <div class="col-md-12">
            <div class="media">
                <div class="media-left">
                    <a ><span class="glyphicon glyphicon-envelope"></span>{{ v.name }}</a>

                </div>
                <div class="media-body">
                    <h4>
                    <a  class="label label-primary pull-right">{{ v.address }} --- {{ v.create_time  }}</a>
                    </h4>
                    {{v.message}}

                </div>
            </div>
        </div>
        {% endfor %}

         <!--
         可加入分页功能
         -->
    </div>
</div>
<!--内容-->

{% endblock %}