DjangoBooks/DjangoBooks/urls.py
from django.conf.urls import url, include
# from django.contrib import admin
from django.views.generic import RedirectView
from books.index_handle import index_handle

import xadmin
"""
第一种首页配置url(r"^index/$", index_handle.index_handle), 采用一级路由
第二种首页配置url(r'^$',RedirectView.as_view(url= "books/index")), 采用二级路由重定向路径
"""
urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    # url(r'^$',index_handle),
    url(r'^xadmin/',xadmin.site.urls),
    url(r'^ueditor/',include('DjangoUeditor.urls')),
    url(r'^$',RedirectView.as_view(url= "books/index")),
    url(r'^books/',include('books.urls')),
    url(r'^user/',include('user_center.urls')),
    url(r'^message/',include('message.urls')),
    url(r'^apis/', include("drf_apis.urls")),
    url(r'^statistic/',include('statistic.urls')),
    url(r'^cart/',include('commerce.urls')),
]

DjangoBooks/apps/books/urls.py
from django.conf.urls import url
from books import index_handle,add_handler,detail_handler,art_capter_handler,search_handler

app_name = "books"
urlpatterns = [
    url(r"^index/$", index_handle.index_handle),
    # url(r"^add/$",add_handler.AddHandler),
    url(r"^detail/$",detail_handler.detail_handler),
    url(r'^capter/$',art_capter_handler.ArtCapterHandler),
    url(r'^search/$',search_handler.search_handler),
]

DjangoBooks/apps/message/urls.py
from django.conf.urls import url

from message import message_handler, comments_handler

"""
第一种首页配置url(r"^index/$", index_handle.index_handle), 采用一级路由
第二种首页配置url(r'^$',RedirectView.as_view(url= "books/index")), 采用二级路由重定向路径
"""
app_name = "message"
urlpatterns = [
    url(r'^art/(?P<art_pk>[0-9]+)/$',comments_handler.art_comment,name="art_comment"),
    url(r"^$", message_handler.MessageSubmitHandlerV2, name='msg_form'),
]

DjangoBooks/extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

DjangoBooks/apps/books/models.py
from DjangoUeditor.models import UEditorField
from django.db import models
from django.utils import timezone
from DjangoBooks.settings import DB_FIELD_VALID_CHOICES

"""
timezone.now 为了保证所有地区时间一致
如果网站面向的是多个时区用户，只以当前时间为标准开发，便会在时间计算上产生错误。
最好USE_TZ = True 同时安装 pytz 模块(pip install pytz) 。
verbose_name_plural = "学校"
如果不指定Django会自动在模型名称后加一个’s’
"""


class Tag(models.Model):
    t_name = models.CharField(max_length=60, verbose_name='书名字')
    t_info = models.CharField(max_length=60, verbose_name='书分类')
    t_createtime = models.DateTimeField(default=timezone.now, db_index=True, verbose_name='创建时间')
    t_flag = models.IntegerField(default=0, verbose_name='控制字段', choices=DB_FIELD_VALID_CHOICES)

    def __str__(self):
        return self.t_name

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name
        db_table = 'tag'
        # ordering这是一个字符串的元组或列表,更具字段排序默认升序 '-' 降序
        ordering = ["-t_createtime"]


class Art(models.Model):
    a_title = models.CharField(max_length=100, verbose_name='书名')
    a_info = models.CharField(max_length=200, verbose_name='书分类')
    # a_content = models.TextField(max_length=500,verbose_name='书详情介绍')
    a_content = UEditorField(verbose_name="文章内容", width=1000, height=600,
                             imagePath="media/arts_ups/ueditor/",
                             filePath="media/arts_ups/ueditor/",
                             blank=True, toolbars="full", default='')
    a_img = models.ImageField(null=True, blank=True, upload_to='media/arts_ups/%Y/%m',
                              verbose_name='封面', max_length=150
                              )
    a_createtime = models.DateTimeField(default=timezone.now, db_index=True,
                                        verbose_name="添加时间")
    a_tag = models.ForeignKey(Tag, verbose_name="关联文章标签")
    a_price = models.IntegerField(default=0, verbose_name="单价")
    a_flag = models.IntegerField(default=0, verbose_name="控制字段", choices=DB_FIELD_VALID_CHOICES)
    operator = models.ForeignKey('auth.User', default=1, verbose_name='api操作者')

    # 和后台用户建立外键auth.User
    def __str__(self):
        return self.a_title

    class Meta:
        verbose_name = '小说'
        verbose_name_plural = verbose_name
        db_table = 'art'
        ordering = ['-a_createtime']


class Chapter(models.Model):
    art = models.ForeignKey(Art, verbose_name='小说')
    title = models.CharField(max_length=100, verbose_name='章节标题')
    content = models.TextField(verbose_name="小说章节内容")
    create_time = models.DateTimeField(default=timezone.now, db_index=True,
                                       verbose_name="添加时间")

    class Meta:
        db_table = "art_chapter"
        verbose_name = "小说章节"
        verbose_name_plural = verbose_name

DjangoBooks/apps/books/views.py
from django.shortcuts import render

# Create your views here.

DjangoBooks/apps/books/templates/capter_handler.html
{% extends "base_tmp.html" %}

{% block content %}
<!--内容-->
<div class="container" style="margin-top:76px">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title"><span class="glyphicon glyphicon-list-alt"></span>{{art_capter.art.a_title}}  章节详情</h3>
                </div>
                <div class="panel-body">
                    <h1 class="text-center">{{ art_capter.title }}</h1>
                    <div style="color: green;" align="center">
                        时间:<span>{{art_capter.create_time}}</span>
                    </div>
                    <br>
                    {% for art in art_capter.content %}
                    <a><span style="font-size: 30px">{{art}}</span></a><br>
                    {% endfor %}


                </div>


            </div>
        </div>

    </div>


</div>
<!--内容-->
{% endblock %}

DjangoBooks/apps/books/templates/carousel.html
<div class="container" id="myCarousel" style="margin-top:80px">
		<!-- 轮播图容器 -->
		<div id="carousel-example-generic" class="carousel slide">
			<!-- 轮播图上的圆圈链接 -->
			<ol class="carousel-indicators radiou">
				<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
				<li data-target="#carousel-example-generic" data-slide-to="1"></li>
				<li data-target="#carousel-example-generic" data-slide-to="2"></li>
                <li data-target="#carousel-example-generic" data-slide-to="3"></li>
			</ol>
			<!-- 轮播图具体内容 -->
			<div class="carousel-inner">
				<div class="item active">
					<img src="/static/images/fengmian1.jpeg" style="background-size:cover; height: 300px; width:1200px">
					<!-- 图上文字 -->
					<div class="carousel-caption">
						<h4>美丽俏佳人</h4>
						<p>美丽俏佳人</p>
					</div>
				</div>
				<div class="item">
					<img src="/static/images/shanhaijing.jpeg" style="background-size:cover; height: 300px; width:1200px">
					<!-- 图上文字 -->
					<div class="carousel-caption">
						<h4>山海经</h4>
						<p>山海经 密码</p>
					</div>
				</div>
				<div class="item">
                    <img src="/static/images/hudie.jpeg" style="background-size:cover; height: 300px; width:1200px">
					<!-- 图上文字 -->
					<div class="carousel-caption">
						<h4>新鸳鸯蝴蝶梦</h4>
						<p>新鸳鸯蝴蝶梦 名著</p>
					</div>
				</div>
                <div class="item">
                    <img src="/static/images/liangcheng.jpeg" style="background-size:cover; height: 300px; width:1200px">
					<!-- 图上文字 -->
					<div class="carousel-caption">
						<h4>凉城以北</h4>
						<p>凉城以北</p>
					</div>
				</div>
			</div>
			<!-- 轮播图上的向前一图切换链接 -->
			<a href="#carousel-example-generic" data-slide="prev" class="left carousel-control">
				<span class="glyphicon glyphicon-chevron-left"></span>
			</a>
			<!-- 轮播图上的向后一图切换链接 -->
			<a href="#carousel-example-generic" data-slide="next" class="right carousel-control">
				<span class="glyphicon glyphicon-chevron-right"></span>
			</a>
		</div>
	</div>

DjangoBooks/apps/books/templates/detail_handler.html
{% extends "base_tmp.html" %}


{% block content %}
    <!--内容-->
    <div class="container" style="margin-top:76px">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h3 class="panel-title"><span class="glyphicon glyphicon-list-alt"></span>&nbsp;小说详情</h3>
                    </div>
                    <div class="panel-body">
                        <h1 class="text-center">{{ art.a_title }}</h1>
                        <div align="center">
                            <a style="font-size: 18px;">价格:<span style="color: green"> {{ art.a_price }}</span>元</a>
                        </div>

                        <div class="span" align="right">
                            <a class="btn primary btn-success" type="button"
                               href="/cart/add?id={{ art.id }}">加入购物车</a>

                            <a class="btn primary btn-danger" type="button"
                               href="/cart/order">我的订单</a>

                        </div>


                        <div class="col-md-3">
                            <img data-original="/static/images/full/
{{ art.a_img }}.jpg" style="width:262px;height:166px;"
                                 class="img-responsive center-block lazy" alt="">
                        </div>
                        <div class="col-md-9">

                            {{ art.a_content | safe }}

                        </div>

                    </div>

                    <!-- ArtsTab begin -->
                    <ul id="ArtsTab" class="nav nav-tabs" style="margin-top: 50px;">
                        <li class="active">
                            <a href="#catalog" data-toggle="tab" style="color: cadetblue;font-size: 20px;">
                                小说章节
                            </a>
                        </li>
                        <li>
                            <a href="#discuss" data-toggle="tab" style="color: cadetblue;font-size: 20px;">
                                讨论区
                            </a>
                        </li>
                    </ul>

                    <div id="ArtsTabContent" class="tab-content">
                        <div class="tab-pane fade in active" id="catalog">

                            <h3 align="center">{{ art.a_title }} 章节 </h3>
                            <ul class="list-group">
                                {% for capter in art_capters %}
                                    <a class="list-group-item"
                                       href="/books/capter?id={{ capter.id }}">{{ capter.title }}</a>
                                {% endfor %}
                            </ul>

                        </div>
                        <div class="tab-pane fade" id="discuss">

                            <h3 align="center">{{ art.a_title }} 的讨论区 </h3>
                            <!--- 评论区表单 --->
                            <form action="{% url 'message:art_comment' art.pk %}" method="post" class="comment-form">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-md-12">
                                        <label for="{{ form.name.id_for_label }}">名字：</label>
                                        {{ form.name }}
                                        {{ form.name.errors }}
                                    </div>
                                    <div class="col-md-12">
                                        <label for="{{ form.title.id_for_label }}">标题：</label>
                                        {{ form.title }}
                                        {{ form.title.errors }}
                                    </div>

                                    <div class="col-md-12">
                                        <label for="{{ form.text.id_for_label }}">评论：</label>
                                        <br>
                                        {{ form.text }}
                                        {{ form.text.errors }}
                                        <br>
                                        <button type="submit" class="comment-btn btn-success">发表评论</button>
                                    </div>
                                </div>    <!-- row -->
                            </form>
                            <!--- 评论区表单 --->
                            <br>

                            <div class="comment-list-pannel">
                                <h3>评论列表， 共<span>{{ comment_count }}</span>条评论</h3>
                                <hr>
                                <ul class="comment-list list-unstyled">
                                    {% for comment in comment_list %}
                                        <span class="glyphicon glyphicon-user label label-primary"> {{ comment.name }}</span>
                                        <span class="glyphicon glyphicon-time label label-success">{{ comment.created_time }}</span>
                                        <br><br>
                                        <div class="text">
                                            {{ comment.text }}
                                        </div>
                                        <hr>
                                    {% endfor %}
                                </ul>
                            </div>


                        </div>
                    </div>

                    <!-- ArtsTab end -->


                </div>
            </div>

        </div>

    </div>
    <!--内容-->
{% endblock %}

DjangoBooks/apps/books/templates/index_handler.html
{% extends "base_tmp.html" %}

{% block carousel %}

    {% include "carousel.html" %}

{% endblock %}

{% block content %}
<!--文章列表-->
<section id="artlist" style="margin-top:0px">
    <div class="container">
        <div class="row wow fadeIn" data-wow-delay="0.6s">
            <div class="col-md-12 table-responsive">
                <table class="table text-left table-bordered" id="arttags">
                    <tr>
                        <td style="width:10%;">文章标签</td>
                        <td style="width:90%;">
                             <a class="label label-info" id="curtag0" href="{{url}}?t=0"><span
                                    class="glyphicon glyphicon-tag"></span>&nbsp;全部</a>
                            {% for tag in tags %}
                            <a class="label label-info" id="curtag{{tag.id}}" href="{{url}}?t={{tag.id}}"><span
                                    class="glyphicon glyphicon-tag"></span>&nbsp;{{tag.t_name}}</a>
                            &nbsp;
                            {% endfor %}
                        </td>
                    </tr>
                </table>
            </div>
            {% for v in  data %}
            <div class="col-md-3">
                <div class="artlist text-center">

                    <img data-original="/static/images/full/{{v.a_img}}.jpg"  style="width:262px;height:250px;"
                         class="img-responsive center-block lazy" alt="">
                    <br>
                    <div class="text-left" style="margin-left:auto;margin-right:auto;width:250px;">
                        <span style="color: #0f0f0f;font-size: 18px; font-weight: bold">{{v.a_title}}</span><br>
                        <br>
                        <p style="height: 50px;overflow:hidden;text-overflow: ellipsis;white-space: nowrap">{{v.a_info}}</p>
                    </div>

                    <a href="/books/detail?id={{v.id}}" class="btn btn-primary" target="_blank" role="button">
                        <span class="glyphicon glyphicon-eye-open"></span>&nbsp;阅读</a>
                </div>
            </div>
            {% endfor %}

            <div class="col-md-12 text-center" style="margin-top:12px;">
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        <li>
                            <a href="{{url}}?page=1&t={{t}}" aria-label="First">
                                <span aria-hidden="true">首页</span>
                            </a>
                        </li>
                        <li>
                            {% if p.has_previous %}
                              <a href="{{url}}?page={{p.previous_page_number}}&t={{t}}"
                               aria-label="Previous">
                                <span aria-hidden="true">上一页</span>
                            </a>
                                {% else %}
                                  <a href="{{url}}?page=1&t={{t}}"
                               aria-label="Previous">
                                <span aria-hidden="true">上一页</span>
                            </a>
                            {% endif %}

                        </li>

                        {% for v in pagerange %}
                        {% if v == page %}
                        <li class="active"><a href="{{url}}?page={{ v }}&t={{t}}">{{v}}</a></li>
                        {% else %}
                        <li><a href="{{url}}?page={{ v }}&t={{t}}">{{ v }}</a></li>
                        {% endif %}
                        {% endfor %}


{#                        <li>#}
{#                            <a href="{{url}}?page={{next}}&t={{t}}"#}
{#                               aria-label="Next">#}
{#                                <span aria-hidden="true">下一页</span>#}
{#                            </a>#}
{#                        </li>#}
                        <li>
                            {% if p.has_next %}
                              <a href="{{url}}?page={{p.next_page_number}}&t={{t}}"
                               aria-label="Next">
                                <span aria-hidden="true">下一页</span>
                            </a>
                                {% else %}
                                 <a href="{{url}}?page={{p.num_pages}}&t={{t}}"
                               aria-label="Next">
                                <span aria-hidden="true">下一页</span>
                            </a>
                            {% endif %}

                        </li>


                        <li>
                            <a href="{{url}}?page={{p.num_pages}}&t={{t}}"
                               aria-label="Last">
                                <span aria-hidden="true">尾页</span>
                            </a>
                        </li>
                    </ul>
                </nav>
                <a class="label label-success" style="display:inline-block;width:150px;">共{{p.num_pages}}页</a>
                &nbsp;
                <a class="label label-info" style="display:inline-block;width:150px;">共{{p.count}}条记录</a>
            </div>
        </div>
    </div>
</section>
<!--电影列表-->
<!--电影列表-->
{% endblock %}

{% block js %}
<script>
    $(document).ready(function(){
        $("#curtag{{t}}").attr("class","label label-danger");
    });
</script>


{% endblock %}

DjangoBooks/apps/books/templates/search_handler.html
{% extends "base_tmp.html" %}

{% block content %}
<!--内容-->
<div class="container" style="margin-top:76px">
    <div class="row">
        <div class="col-md-12">
            <ol class="breadcrumb" style="margin-top:6px;">
                <li>与"{{key}}"有关的文章，共{{p.count}}篇</li>
            </ol>
        </div>
        {% for v in  data %}
        <div class="col-md-12">
            <div class="media">
                <div class="media-left">
                    <a href="/books/detail?id={{v.id}}">
                        <img class="media-object" src="/static/images/full/{{v.a_img}}.jpg" style="width:131px;height:83px;" alt="{{v.a_title}}">
                    </a>
                </div>
                <div class="media-body">
                    <h4 class="media-heading">{{v.a_title}}<a href="/books/detail?id={{v.id}}" class="label label-primary pull-right"><span
                            class="glyphicon glyphicon-eye-open"></span>阅读文章</a></h4>
                    {{v.a_info}}
                </div>
            </div>
        </div>
        {% endfor %}
        <div class="col-md-12 text-center" style="margin-top:12px;">
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    <li>
                        <a href="{{url}}?page=1&key={{key}}" aria-label="First">
                            <span aria-hidden="true">首页</span>
                        </a>
                    </li>
                    <li>
                        {% if p.has_previous %}
                          <a href="{{url}}?page={{p.previous_page_number}}&key={{key}}"
                           aria-label="Previous">
                            <span aria-hidden="true">上一页</span>
                        </a>
                         {% else %}
                            <a href="{{url}}?page=1&key={{key}}"
                           aria-label="Previous">
                            <span aria-hidden="true">上一页</span>
                        </a>
                        {% endif %}

                    </li>
                    {% for v in pagerange %}
                    {% if v == page %}
                    <li class="active"><a href="{{url}}?page={{ v }}&key={{key}}">{{v}}</a></li>
                    {% else %}
                    <li><a href="{{url}}?page={{ v }}&key={{key}}">{{ v }}</a></li>
                    {% endif %}
                    {% endfor %}
                    <li>
                         {% if p.has_next %}
                         <a href="{{url}}?page={{p.next_page_number}}&key={{key}}"
                           aria-label="Next">
                            <span aria-hidden="true">下一页</span>
                        </a>
                             {% else %}
                               <a href="{{url}}?page={{p.num_pages}}&key={{key}}"
                           aria-label="Next">
                            <span aria-hidden="true">下一页</span>
                        </a>

                        {% endif %}

                    </li>
                    <li>
                        <a href="{{url}}?page={{p.num_pages}}&key={{key}}"
                           aria-label="Last">
                            <span aria-hidden="true">尾页</span>
                        </a>
                    </li>
                </ul>
            </nav>
            <a class="label label-success" style="display:inline-block;width:150px;">共{{p.num_pages}}页</a>
            &nbsp;
            <a class="label label-info" style="display:inline-block;width:150px;">共{{p.count}}条记录</a>
        </div>
    </div>
</div>
<!--内容-->
{% endblock %}